# Generated by Django 4.2.7 on 2023-11-28 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('send_private_email', 'Can send private email to user bye the button')]},
        ),
    ]
